/*
View Name: Q_BCR_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-bcr-all-payor-source.md for full documentation.
*/

-- ALTER VIEW dbo.Q_BCR_ALL_PAYOR_SOURCE AS
SELECT BPAY.ID,
	BPAY.DOCSERNO,
	BPAY.DOCREVNO,
	CAST(BPAY.VISITDT AS DATE) AS [VISIT_DATE],
	BPAY.VISITTM AS [VISIT_TIME],
	BPAY.USERID,
	COALESCE(BIC.DOCSERNO, BPAY.PARENTDOCSERNO) AS [PARENT_DOCSERNO],
	BPF.FORM_TYPE,
	BPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(BPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BPAY.PAYOR_SOURCE,
	BPAY.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	BPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(BPAY.PAYOR_SOURCE_START_DATE AS DATE) AS [PAYOR_SOURCE_START_DATE],
	CAST(BPAY.PAYOR_SOURCE_END_DATE AS DATE) AS [PAYOR_SOURCE_END_DATE]
FROM DBO.PWPAYORSOURCE AS [BPAY]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON BPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PWBCRINITIALCONTACT AS [BIC]
	ON BPAY.CLIENTNUMBER = BIC.CLIENTNUMBER
	AND BPAY.PATHWAY_DATE = BIC.PATHWAY_DATE
	AND BPAY.USERID LIKE 'import%'
LEFT JOIN DBO.Q_BCR_PATHWAY_FORM_DOCSERNOS AS [BPF]
	ON COALESCE(BPAY.PARENTDOCSERNO, BIC.DOCSERNO) = BPF.DOCSERNO
WHERE BPAY.DOCREVNO = ' 0 '
	AND COALESCE(BPAY.PARENTDOCSERNO, BIC.DOCSERNO) IN (
			SELECT BPF.DOCSERNO 
			FROM DBO.Q_BCR_PATHWAY_FORM_DOCSERNOS AS [BPF]
	);