/*
View Name: Q_BCR_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-bcr-all-housing-status.md for full documentation.
*/

-- ALTER VIEW dbo.Q_BCR_ALL_HOUSING_STATUS AS
SELECT BHOUSE.ID,
	BHOUSE.DOCSERNO,
	CAST(BHOUSE.VISITDT AS DATE) AS [VISIT_DATE],
	BHOUSE.VISITTM AS [VISIT_TIME],
	BHOUSE.USERID,
	COALESCE(BHOUSE.PARENTDOCSERNO, BIC.DOCSERNO) AS [PARENT_DOCSERNO],
	BPF.FORM_TYPE,
	BPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(BHOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BHOUSE.CLIENT_HOUSING_STATUS,
	BHOUSE.HOUSING_STATUS_INCARCERATED,
	BHOUSE.UNHOUSED_SHELTER,
	BHOUSE.IF_UNHOUSED_EXP,
	BHOUSE.WORRIED_LOSING_HOUSING,
	CAST(BHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(BHOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	BHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(BHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(BHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(BHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(BHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(BHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM DBO.PWHOUSINGSTATUS AS [BHOUSE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON BHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PWBCRINITIALCONTACT AS [BIC]
	ON BHOUSE.CLIENTNUMBER = BIC.CLIENTNUMBER
	AND BHOUSE.PATHWAY_DATE = BIC.PATHWAY_DATE
	AND BHOUSE.USERID LIKE 'import%'
LEFT JOIN DBO.Q_BCR_PATHWAY_FORM_DOCSERNOS AS [BPF]
	ON COALESCE(BHOUSE.PARENTDOCSERNO, BIC.DOCSERNO) = BPF.DOCSERNO
WHERE BHOUSE.DOCREVNO = ' 0 '
	AND COALESCE(BHOUSE.PARENTDOCSERNO, BIC.DOCSERNO) IN (
			SELECT BPF.DOCSERNO 
			FROM DBO.Q_BCR_PATHWAY_FORM_DOCSERNOS AS [BPF]
	);