/*
View Name: Q_COMPLEX_CARE_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-complex-care-all-payor-source.md for full documentation.
*/

-- ALTER VIEW .dbo.Q_COMPLEX_CARE_ALL_PAYOR_SOURCE AS
SELECT CPAY.ID,
	CPAY.DOCSERNO,
	CAST(CPAY.VISITDT AS DATE) AS [VISIT_DATE],
	CPAY.VISITTM AS [VISIT_TIME],
	CPAY.USERID,
	CPAY.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CPF.FORM_TYPE,
	CPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(CPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CPAY.PAYOR_SOURCE AS [PAYOR_SOURCE_CODE],
	PAYSRC.DESCRIPTION AS [PAYOR_SOURCE_DESCRIPTION],
	CPAY.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	CPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(CPAY.PAYOR_SOURCE_START_DATE AS DATE) AS [PAYOR_SOURCE_START_DATE],
	CAST(CPAY.PAYOR_SOURCE_END_DATE AS DATE) AS [PAYOR_SOURCE_END_DATE]
FROM DBO.PWPAYORSOURCE AS [CPAY]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON CPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PAYOR_SOURCE AS [PAYSRC]
	 ON PAYSRC.CODE = CPAY.PAYOR_SOURCE
INNER JOIN DBO.Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
	ON CPAY.CLIENTNUMBER = CBENCH.CLIENT_NUMBER
	AND CPAY.PARENTDOCSERNO = CBENCH.DOCSERNO
LEFT JOIN DBO.Q_COMPLEX_CARE_PATHWAY_FORM_DOCSERNOS AS [CPF]
	 ON CPAY.PARENTDOCSERNO = CPF.DOCSERNO
WHERE CPAY.DOCREVNO = ' 0 '