/*
View Name: Q_COMPLEX_CARE_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-all-housing-status.md for full documentation.
*/

-- CREATE VIEW dbo.Q_COMPLEX_CARE_ALL_HOUSING_STATUS AS
SELECT CHOUSE.ID,
	CHOUSE.DOCSERNO,
	CHOUSE.DOCREVNO,
	CAST(CHOUSE.VISITDT AS DATE) AS [VISIT_DATE],
	CHOUSE.VISITTM AS [VISIT_TIME],
	CHOUSE.USERID,
	CHOUSE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CENROLL.PWY_EVENT AS [FORM_TYPE],
	CENROLL.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(CHOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CHOUSE.CLIENT_HOUSING_STATUS,
	CHOUSE.HOUSING_STATUS_INCARCERATED,
	CHOUSE.UNHOUSED_SHELTER,
	CHOUSE.IF_UNHOUSED_EXP,
	CHOUSE.WORRIED_LOSING_HOUSING,
	CAST(CHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(CHOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	CHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(CHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(CHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(CHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(CHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(CHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM DBO.PWHOUSINGSTATUS AS [CHOUSE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON CHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
INNER JOIN DBO.Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
	ON CHOUSE.CLIENTNUMBER = CBENCH.CLIENT_NUMBER
	AND CHOUSE.PARENTDOCSERNO = CBENCH.DOCSERNO
INNER JOIN DBO.Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
	ON CHOUSE.CLIENTNUMBER = CENROLL.CLIENT_NUMBER
	AND CBENCH.TIEDENROLLMENT = CENROLL.TIEDENROLLMENT
	AND CENROLL.PWY_EVENT = 'Clinical BEACN Metrics'
WHERE CHOUSE.DOCREVNO = ' 0 ';