/*
View Name: Q_EPICC_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-payor-source.md for full documentation.
*/

-- ALTER VIEW .dbo.Q_EPICC_ALL_PAYOR_SOURCE AS
SELECT EPAY.ID,
	EPAY.DOCSERNO,
	EPAY.DOCREVNO,
	CAST(EPAY.VISITDT AS DATE) AS [VISIT_DATE],
	EPAY.VISITTM AS [VISIT_TIME],
	EPAY.USERID,
	COALESCE(EIC.DOCSERNO, EPAY.PARENTDOCSERNO) AS [PARENT_DOCSERNO],
	EPF.FORM_TYPE,
	EPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EPAY.PAYOR_SOURCE AS [PAYOR_SOURCE_CODE],
	PAY.DESCRIPTION AS [PAYOR_SOURCE_DESCRIPTION],
	EPAY.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	EPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(EPAY.PAYOR_SOURCE_START_DATE AS DATE) AS [PAYOR_SOURCE_START_DATE],
	CAST(EPAY.PAYOR_SOURCE_END_DATE AS DATE) AS [PAYOR_SOURCE_END_DATE]
FROM DBO.PWPAYORSOURCE AS [EPAY]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PWEPICCINITIALCONTACT AS [EIC]
	ON EPAY.CLIENTNUMBER = EIC.CLIENTNUMBER
	AND EPAY.PATHWAY_DATE = EIC.PATHWAY_DATE
	AND EPAY.USERID LIKE 'import%'
LEFT JOIN DBO.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	ON COALESCE(EPAY.PARENTDOCSERNO, EIC.DOCSERNO) = EPF.DOCSERNO
LEFT JOIN DBO.PAYOR_SOURCE AS [PAY]
	ON EPAY.PAYOR_SOURCE = PAY.CODE
LEFT JOIN DBO.MANAGED_MEDICAID_PROVIDER AS [MMP]
	ON EPAY.MANAGED_MEDICAID_PROVIDER = MMP.CODE
WHERE EPAY.DOCREVNO = ' 0 '
	AND COALESCE(EPAY.PARENTDOCSERNO, EIC.DOCSERNO) IN (
			SELECT EPF.DOCSERNO 
			FROM DBO.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	);