/*
View Name: Q_EPICC_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-housing-status.md for full documentation.
*/

-- ALTER VIEW dbo.Q_EPICC_ALL_HOUSING_STATUS AS
SELECT EHOUSE.ID,
	EHOUSE.DOCSERNO,
	EHOUSE.DOCREVNO,
	CAST(EHOUSE.VISITDT AS DATE) AS [VISIT_DATE],
	EHOUSE.VISITTM AS [VISIT_TIME],
	EHOUSE.USERID,
	COALESCE(EHOUSE.PARENTDOCSERNO, EIC.DOCSERNO) AS [PARENT_DOCSERNO],
	EPF.FORM_TYPE,
	EPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EHOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EHOUSE.CLIENT_HOUSING_STATUS,
	EHOUSE.HOUSING_STATUS_INCARCERATED,
	EHOUSE.UNHOUSED_SHELTER,
	EHOUSE.IF_UNHOUSED_EXP,
	EHOUSE.WORRIED_LOSING_HOUSING,
	CAST(EHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(EHOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	EHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(EHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(EHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(EHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(EHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(EHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM DBO.PWHOUSINGSTATUS AS [EHOUSE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.Q_EPICC_IC AS [EIC]
    ON EHOUSE.CLIENTNUMBER = EIC.CLIENT_NUMBER
    AND EHOUSE.PATHWAY_DATE = EIC.PATHWAY_DATE
    AND EHOUSE.USERID LIKE 'import%'
LEFT JOIN DBO.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	ON COALESCE(EHOUSE.PARENTDOCSERNO, EIC.DOCSERNO) = EPF.DOCSERNO
WHERE EHOUSE.DOCREVNO = ' 0 '
	AND COALESCE(EHOUSE.PARENTDOCSERNO, EIC.DOCSERNO) IN (
			SELECT EPF.DOCSERNO 
			FROM DBO.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	);