/*
View Name: Q_ERE_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-ere-all-housing-status.md for full documentation.
*/

-- ALTER VIEW dbo.Q_ERE_ALL_HOUSING_STATUS AS
SELECT EREHOUSE.ID,
	EREHOUSE.DOCSERNO,
	CAST(EREHOUSE.VISITDT AS DATE) AS [VISIT_DATE],
	EREHOUSE.VISITTM AS [VISIT_TIME],
	EREHOUSE.USERID,
	COALESCE(EREHOUSE.PARENTDOCSERNO, EREIHNA.DOCSERNO) AS [PARENT_DOCSERNO],
	EREPF.FORM_TYPE,
	EREPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EREHOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREHOUSE.CLIENT_HOUSING_STATUS,
	EREHOUSE.HOUSING_STATUS_INCARCERATED,
	EREHOUSE.UNHOUSED_SHELTER,
	EREHOUSE.IF_UNHOUSED_EXP,
	EREHOUSE.WORRIED_LOSING_HOUSING,
	CAST(EREHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(EREHOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	EREHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(EREHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(EREHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(EREHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(EREHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(EREHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM DBO.PWHOUSINGSTATUS AS [EREHOUSE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EREHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.Q_ERE_IHNA AS [EREIHNA]
	ON EREHOUSE.CLIENTNUMBER = EREIHNA.CLIENT_NUMBER
	AND EREHOUSE.PATHWAY_DATE = EREIHNA.PATHWAY_DATE
	AND EREHOUSE.USERID LIKE 'import%'
LEFT JOIN DBO.Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	ON COALESCE(EREHOUSE.PARENTDOCSERNO, EREIHNA.DOCSERNO) = EREPF.DOCSERNO
WHERE EREHOUSE.DOCREVNO = ' 0 '
	AND COALESCE(EREHOUSE.PARENTDOCSERNO, EREIHNA.DOCSERNO) IN (
			SELECT EREPF.DOCSERNO 
			FROM DBO.Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	);