/*
View Name: Q_ERE_THREE_MONTH  
Category: View Definitions  

See docs/view-definitions/q-ere-three-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_ERE_THREE_MONTH AS
SELECT ERETHREEM.ID,
	ERETHREEM.DOCSERNO,
	ERETHREEM.TIEDENROLLMENT,
	ERETHREEM.PARENTDOCSERNO,
	CAST(ERETHREEM.VISITDT AS DATE) AS [VISITDT],
	ERETHREEM.VISITTM,
	ERETHREEM.USERID,
	'ERE 3 Month' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(ERETHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERETHREEM.COMPLETION_HELPER_THREE_MONTH,
	ERETHREEM.OTHER_COMPLETION_HELPER_THREE_MONTH,
	ERETHREEM.METHOD_OF_CONTACT_THREE_MONTH,
	ERETHREEM.METHOD_OF_CONTACT_OTHER_THREE_MONTH,
	ERETHREEM.STILL_ENGAGED_ERE_SERVICES_THREE_MONTH,
	ERETHREEM.INELIGIBLE_REASON_THREE_MONTH,
	ERETHREEM.CONTACT_RESULT_PPC_THREE_MONTH,
	ERETHREEM.EMPLOYMENT_STATUS_THREE_MONTH AS [EMPLOYMENT_STATUS_THREE_MONTH_CODE],
	EMPSTATUS.DESCRIPTION AS [EMPLOYMENT_STATUS_THREE_MONTH_DESCRIPTION],
	ERETHREEM.NUM_ER_VISITS_PAST_THREE_MONTHS_THREE_MONTH,
	ERETHREEM.NUM_HOSP_PAST_THREE_MONTHS_THREE_MONTH,
	ERETHREEM.NUM_LEO_CONTACTS_PAST_THREE_MONTHS_THREE_MONTH
FROM DBO.PWERETHREEMONTHFOLLOWUP AS [ERETHREEM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON ERETHREEM.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.ERE_EMPLOY_STATUS AS [EMPSTATUS]
	ON ERETHREEM.EMPLOYMENT_STATUS_THREE_MONTH = EMPSTATUS.CODE
WHERE ERETHREEM.DOCREVNO = ' 0 ';