/*
View Name: Q_ERE_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-ere-all-payor-source.md for full documentation.
*/

--ALTER VIEW .dbo.Q_ERE_ALL_PAYOR_SOURCE AS
SELECT EREPAY.ID,
	EREPAY.DOCSERNO,
	EREPAY.DOCREVNO,
	CAST(EREPAY.VISITDT AS DATE) AS [VISIT_DATE],
	EREPAY.VISITTM AS [VISIT_TIME],
	EREPAY.USERID,
	EREPAY.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	EREPF.FORM_TYPE,
	EREPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EREPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREPAY.PAYOR_SOURCE AS [PAYOR_SOURCE_CODE],
	PAY.DESCRIPTION AS [PAYOR_SOURCE_DESCRIPTION],
	EREPAY.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	EREPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(EREPAY.PAYOR_SOURCE_START_DATE AS DATE) AS [PAYOR_SOURCE_START_DATE],
	CAST(EREPAY.PAYOR_SOURCE_END_DATE AS DATE) AS [PAYOR_SOURCE_END_DATE]
FROM DBO.PWPAYORSOURCE AS [EREPAY]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EREPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	ON EREPAY.PARENTDOCSERNO = EREPF.DOCSERNO
LEFT JOIN DBO.PAYOR_SOURCE AS [PAY]
	ON EREPAY.PAYOR_SOURCE = PAY.CODE
LEFT JOIN DBO.MANAGED_MEDICAID_PROVIDER AS [MMP]
	ON EREPAY.MANAGED_MEDICAID_PROVIDER = MMP.CODE
WHERE EREPAY.DOCREVNO = ' 0 '
	AND EREPAY.PARENTDOCSERNO IN (
			SELECT EREPF.DOCSERNO 
			FROM DBO.Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	);