/*
View Name: Q_ERE_IHNA  
Category: View Definitions  

See docs/view-definitions/q-ere-ihna.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_ERE_IHNA AS
SELECT IHNA.ID,
	IHNA.DOCSERNO,
	IHNA.TIEDENROLLMENT,
	CAST(IHNA.VISITDT AS DATE) AS [VISITDT],
	IHNA.VISITTM,
	IHNA.USERID,
	'ERE IHNA' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(IHNA.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	IHNA.COMPLETION_HELPER_IHNA,
	IHNA.OTHER_COMPLETION_HELPER_IHNA,
	IHNA.METHOD_OF_CONTACT_IHNA,
	IHNA.METHOD_OF_CONTACT_OTHER_IHNA,
	IHNA.CONTACT_RESULT_PPC_IHNA,
	IHNA.STILL_ENGAGED_IHNA,
	IHNA.INELIGIBLE_REASON_IHNA,
	ERE_INELIGIBLE_STATUS.DESCRIPTION AS [ERE_INELIGIBLE_STATUS],
	IHNA.MILITARY_STATUS_IHNA,
	IHNA.EMPLOYMENT_STATUS_IHNA AS [EMPLOYMENT_STATUS_IHNA_CODE],
	EMPSTATUS.DESCRIPTION AS [EMPLOYMENT_STATUS_IHNA_DESCRIPTION],
	IHNA.PROBATION_PAROLE_IHNA,
	IHNA.MH_HISTORY,
	IHNA.MH_HX_ADD_ADHD, 
	IHNA.MH_HX_ALZHEIMERS, 
	IHNA.MH_HX_ANTISOCIAL_PERSONALITY_DISORDER, 
	IHNA.MH_HX_AUTISM_SPECTRUM_DISORDER, 
	IHNA.MH_HX_BIPOLAR_DISORDER, 
	IHNA.MH_HX_BORDERLINE_PERSONALITY_DISORDER, 
	IHNA.MH_HX_DD_INTELLECTUAL_DISORDER, 
	IHNA.MH_HX_DELUSIONAL, 
	IHNA.MH_HX_DEMENTIA, 
	IHNA.MH_HX_DEPRESSION, 
	IHNA.MH_HX_EATING_DISORDER, 
	IHNA.MH_HX_OCD, 
	IHNA.MH_HX_PANIC_ANXIETY, 
	IHNA.MH_HX_PTSD, 
	IHNA.MH_HX_SCHIZOPHRENIA, 
	IHNA.MH_HX_SLEEP_DISORDER, 
	IHNA.MH_HX_OTHER_PSYCHIOTIC_DISORDER, 
	IHNA.MH_HX_OTHER, 
	IHNA.MH_HX_UNKNOWN_REFUSED, 
	IHNA.MH_HX_NONSUICIDE_SELFHARM,
	IHNA.MH_HX_SUICIDE_IDEATION_ATTEMPT, 
	IHNA.MH_HX_NONE,
	IHNA.SU_HISTORY,
	IHNA.SU_HX_ALCOHOL, 
	IHNA.SU_HX_COCAINE, 
	IHNA.SU_HX_HALLUCINOGENS, 
	IHNA.SU_HX_HEROIN, 
	IHNA.SU_HX_INHALANTS, 
	IHNA.SU_HX_MARIJUANA, 
	IHNA.SU_HX_METHAMPHETAMINE, 
	IHNA.SU_HX_PRESCRIPTION_OPIOIDS, 
	IHNA.SU_HX_PRESCRIPTION_SEDATIVES, 
	IHNA.SU_HX_PRESCRIPTION_STIMULANTS, 
	IHNA.SU_HX_SYNTHETIC_DRUGS, 
	IHNA.SU_HX_FENTANYL, 
	IHNA.SU_HX_OTHER, 
	IHNA.SU_HX_UNKNOWN_SUBSTANCES, 
	IHNA.SU_HX_NO_SUBSTANCE_USE_HISTORY, 
	IHNA.PHY_HEALTH_HISTORY,
	IHNA.PHY_HX_BMI, 
	IHNA.PHY_HX_CHRONIC_PAIN, 
	IHNA.PHY_HX_CONGESTIVE_HEART_FAILURE, 
	IHNA.PHY_HX_COPD_ASTHMA, 
	IHNA.PHY_HX_DENTAL_CARE, 
	IHNA.PHY_HX_DIABETES, 
	IHNA.PHY_HX_HEPATITIS_C, 
	IHNA.PHY_HX_HYPERTENTION, 
	IHNA.PHY_HX_TOBACCO_USE, 
	IHNA.PHY_HX_OTHER, 
	IHNA.PHY_HX_NO_PHYSICAL_HEALTH_HISTORY, 
	IHNA.NUM_ER_VISITS_PAST_THREE_MONTHS_IHNA,
	IHNA.NUM_HOSP_PAST_THREE_MONTHS_IHNA,
	IHNA.NUM_LEO_CONTACTS_PAST_THREE_MONTHS_IHNA
FROM DBO.PWEREIHNA AS [IHNA]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON IHNA.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.ERE_EMPLOY_STATUS AS [EMPSTATUS]
	ON IHNA.EMPLOYMENT_STATUS_IHNA = EMPSTATUS.CODE
LEFT JOIN DBO.ERE_INELIGIBLE_STATUS AS [ERE_INELIGIBLE_STATUS]
	ON IHNA.INELIGIBLE_REASON_IHNA = ERE_INELIGIBLE_STATUS.CODE
WHERE IHNA.DOCREVNO = ' 0 ';