/*
View Name: Q_YERE_SIX_MONTH
Category: View Definitions  

See docs/view-definitions/q-yere-six-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_SIX_MONTH AS
SELECT YSIXM.ID,
	YSIXM.DOCSERNO,
	YSIXM.TIEDENROLLMENT,
	CAST(YSIXM.VISITDT AS DATE) AS [VISITDT],
	YSIXM.VISITTM,
	YSIXM.USERID,
	YSIXM.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE 6 Month' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(YSIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YSIXM.COMPLETION_HELPER_SIX_MONTH,
	YSIXM.OTHER_COMPLETION_HELPER_SIX_MONTH,
	YSIXM.NAME_OF_PERSON_PROVIDING_RESPONSE,
	YSIXM.RELATIONSHIP_OF_RESPONDENT_TO_CLIENT,
	YSIXM.ACTIVELY_ENGAGED_BH_SERVICES_SIX_MONTH,
	YSIXM.METHOD_CONTACT_SIX_MONTH,
	YSIXM.OTHER_CONTACT_METHOD_SIX_MONTH,
	YSIXM.RESIDENCY_CHANGE_SINCE_REFERRAL_SIX_MONTH,
	YSIXM.RESIDENCY_CHANGE_TYPE_SIX_MONTH,
	YSIXM.SPECIFY_OTHER_RESIDENCY_CHANGE_TYPE_SIX_MONTH,
	YSIXM.CHANGED_SCHOOL_SIX_MONTH,
	YSIXM.ATTEND_SCHOOL_ANY_TIME_THREE_MONTHS_SIX_MONTH,
	YSIXM.NUM_ED_VISITS_PAST_THREE_MONTHS_SIX_MONTH,
	YSIXM.NUM_HOSP_PAST_THREE_MONTHS_SIX_MONTH,
	YSIXM.NUM_LEO_CONTACTS_PAST_THREE_MONTHS_SIX_MONTH,
	YSIXM.INVOLVED_JJ_SYSTEM_PAST_THREE_MONTHS_SIX_MONTH,
	YSIXM.INVOLVEMENT_SRO_SIX_MONTH,
	YSIXM.INVOLVEMENT_WITH_DJO_SIX_MONTH,
	YSIXM.INVOLVEMENT_DYS_SIX_MONTH,
	YSIXM.INVOLVEMENT_WITH_SECURE_DETENTION_SIX_MONTH,
	YSIXM.ATTEND_NEW_BH_INTAKE_BETWEEN_THREE_MONTHS_SIX_MONTH,
	YSIXM.NOTES_SIX_MONTH,
	YSIXM.ImportID
FROM DBO.PWYERE6MONTHFOLLOWUPTP AS [YSIXM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YSIXM.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE YSIXM.DOCREVNO = ' 0 ';