/*
View Name: Q_YERE_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-yere-all-payor-source.md for full documentation.
*/

-- ALTER VIEW .dbo.Q_YERE_ALL_PAYOR_SOURCE AS
SELECT YPAY.ID,
	YPAY.DOCSERNO,
	YPAY.DOCREVNO,
	CAST(YPAY.VISITDT AS DATE) AS [VISIT_DATE],
	YPAY.VISITTM AS [VISIT_TIME],
	YPAY.USERID,
	COALESCE(YIA.DOCSERNO, YPAY.PARENTDOCSERNO) AS [PARENT_DOCSERNO],
	YPF.FORM_TYPE,
	YPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(YPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YPAY.PAYOR_SOURCE AS [PAYOR_SOURCE_CODE],
	PAY.DESCRIPTION AS [PAYOR_SOURCE_DESCRIPTION],
	YPAY.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	YPAY.PRIVATE_INSURANCE_PROVIDER,
    YPAY.SHOW_ME_HEALTHY_KIDS,
	CAST(YPAY.PAYOR_SOURCE_START_DATE AS DATE) AS [PAYOR_SOURCE_START_DATE],
	CAST(YPAY.PAYOR_SOURCE_END_DATE AS DATE) AS [PAYOR_SOURCE_END_DATE]
FROM DBO.PWPAYORSOURCE AS [YPAY]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PWYEREINITIALCONTACT AS [YIA]
	ON YPAY.CLIENTNUMBER = YIA.CLIENTNUMBER
	AND YPAY.PATHWAY_DATE = YIA.PATHWAY_DATE
	AND YPAY.USERID LIKE 'import%'
LEFT JOIN DBO.PAYOR_SOURCE AS [PAY]
	ON YPAY.PAYOR_SOURCE = PAY.CODE
LEFT JOIN DBO.MANAGED_MEDICAID_PROVIDER AS [MMP]
	ON YPAY.MANAGED_MEDICAID_PROVIDER = MMP.CODE
LEFT JOIN DBO.Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	ON COALESCE(YPAY.PARENTDOCSERNO, YIA.DOCSERNO) = YPF.DOCSERNO
WHERE YPAY.DOCREVNO = ' 0 '
	AND COALESCE(YPAY.PARENTDOCSERNO, YIA.DOCSERNO) IN (
			SELECT YPF.DOCSERNO 
			FROM DBO.Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	);