/*
View Name: Q_YERE_THREE_MONTH
Category: View Definitions  

See docs/view-definitions/q-yere-three-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_THREE_MONTH AS
SELECT THREEM.ID,
	THREEM.DOCSERNO,
	THREEM.TIEDENROLLMENT,
	CAST(THREEM.VISITDT AS DATE) AS [VISITDT],
	THREEM.VISITTM,
	THREEM.USERID,
	THREEM.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE 3 Month' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(THREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	THREEM.COMPLETION_HELPER_THREE_MONTH,
	THREEM.OTHER_COMPLETION_HELPER_THREE_MONTH,
	THREEM.STILL_ACTIVELY_ENGAGED_YERE_THREE_MONTH,
	THREEM.METHOD_CONTACT_THREE_MONTH,
	THREEM.OTHER_CONTACT_METHOD_THREE_MONTH,
	THREEM.RESIDENCY_CHANGE_SINCE_REFERRAL_THREE_MONTH,
	THREEM.RESIDENCY_CHANGE_TYPE_THREE_MONTH,
	THREEM.SPECIFY_OTHER_RESIDENCY_CHANGE_TYPE_THREE_MONTH,
	THREEM.RESIDENCY_CHANGE_ADDRESS_EXISTING_BARRIER_SERVICE_PLAN_GOAL_THREE_MONTH,
	THREEM.NUM_ED_VISITS_PAST_THREE_MONTHS_THREE_MONTH,
	THREEM.NUM_HOSP_PAST_THREE_MONTHS_THREE_MONTH,
	THREEM.NUM_LEO_CONTACTS_PAST_THREE_MONTHS_THREE_MONTH,
	THREEM.INVOLVED_JJ_SYSTEM_PAST_THREE_MONTHS_THREE_MONTH,
	THREEM.INVOLVEMENT_SRO_THREE_MONTH,
	THREEM.INVOLVEMENT_DJO_THREE_MONTH,
	THREEM.INVOLVEMENT_DYS_THREE_MONTH,
	THREEM.INVOLVEMENT_SECURE_DETENTION_THREE_MONTH,
	THREEM.CHANGED_SCHOOL_THREE_MONTH,
	THREEM.ATTEND_SCHOOL_ANY_TIME_THREE_MONTHS_THREE_MONTH,
	THREEM.LAST_GRADE_LVL_COMPLETED_THREE_MONTH,
	THREEM.HAVE_HIGH_SCHOOL_EQUIVALENCY_THREE_MONTH,
	THREEM.SEEN_PCP_PAST_TWELVE_MONTHS_THREE_MONTH,
	THREEM.IF_PCP_WHAT_PROVIDER_THREE_MONTH,
	THREEM.SPECIFY_OTHER_OR_PRIVATE_PCP_THREE_MONTH,
	THREEM.ATTEND_NEW_BH_INTAKE_BETWEEN_THIRTY_DAYS_THREE_MONTH,
	THREEM.YOUTH_DLA20_SCORE_THREE_MONTH,
	CAST(THREEM.DATE_YOUTH_DLA20_THREE_MONTH AS DATE) AS [DATE_YOUTH_DLA20_THREE_MONTH],
	THREEM.LEGAL_GUARDIAN_MEET_YERE_FAMILY_SUPPORT_SPECIALIST_THREE_MONTH,
	THREEM.YERE_COLLAB_STAFFING_THREE_MONTH,
	THREEM.ACTIVELY_ENGAGED_BHS_PAST_THIRTY_DAYS_THREE_MONTH,
	THREEM.YERE_SERVICES_EXTENDED_BEYOND_NINETY_DAYS,
	THREEM.NOTES_THIRTY_DAY
FROM DBO.PWYERE3MONTHFOLLOWUPTP AS [THREEM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON THREEM.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE THREEM.DOCREVNO = ' 0 ';