/*
View Name: Q_YERE_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-yere-all-housing-status.md for full documentation.
*/

-- ALTER VIEW dbo.Q_YERE_ALL_HOUSING_STATUS AS
SELECT YHOUSE.ID,
	YHOUSE.DOCSERNO,
	CAST(YHOUSE.VISITDT AS DATE) AS [VISIT_DATE],
	YHOUSE.VISITTM AS [VISIT_TIME],
	YHOUSE.USERID,
	COALESCE(YHOUSE.PARENTDOCSERNO, YIA.DOCSERNO) AS [PARENT_DOCSERNO],
	YPF.FORM_TYPE,
	YPF.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(YHOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YHOUSE.CLIENT_HOUSING_STATUS,
	YHOUSE.HOUSING_STATUS_INCARCERATED,
	YHOUSE.UNHOUSED_SHELTER,
	YHOUSE.IF_UNHOUSED_EXP,
	YHOUSE.WORRIED_LOSING_HOUSING,
	CAST(YHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(YHOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	YHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(YHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(YHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(YHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(YHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(YHOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM DBO.PWHOUSINGSTATUS AS [YHOUSE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.Q_YERE_IA AS [YIA]
	ON YHOUSE.CLIENTNUMBER = YIA.CLIENT_NUMBER
	AND YHOUSE.PATHWAY_DATE = YIA.PATHWAY_DATE
	AND YHOUSE.USERID LIKE 'import%'
LEFT JOIN DBO.Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	ON COALESCE(YHOUSE.PARENTDOCSERNO, YIA.DOCSERNO) = YPF.DOCSERNO
WHERE YHOUSE.DOCREVNO = ' 0 '
	AND COALESCE(YHOUSE.PARENTDOCSERNO, YIA.DOCSERNO) IN (
			SELECT YPF.DOCSERNO 
			FROM DBO.Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	);